R2000:
  transport: "udp"
  scanner_ip: "20.0.10.9"
  # port: "1000" # optional
  device: "R2000"
  start_angle: -1800000
  max_num_points_scan: 0
  packet_type: "C"
  scan_topic: "/scan"
  frame_id: "sensor_laser"
  watchdogtimeout: 60000
  watchdog: true
 